---
- name: Ensure dockerd-rootless-setup.sh is installed
  package:
    name:
      - uidmap
      - slirp4netns
      - docker-ce-rootless-extras
    state: present
  when: ansible_distribution != "CentOS"

- name: Ensure dockerd-rootless-setup.sh is installed
  package:
    name:
      - shadow-utils
      - docker-ce-rootless-extras
    state: present
  when: ansible_distribution == "CentOS"

- name: Stop any running root instances of docker daemon
  service:
    name: docker.service
    state: stopped
    enabled: false

- name: Close root docker socket
  service:
    name: docker.socket
    state: stopped
    enabled: false

- name: Remove docker.sock file
  file:
    path: /var/run/docker.sock
    state: absent

- name: Modprobe ip_tables
  modprobe:
    name: ip_tables

- name: Install rootless docker
  become: false
  command: /usr/bin/dockerd-rootless-setuptool.sh install
  when: rootless_conf.stat.exists == false

- name: Enable and start rootless docker
  become: false
  systemd:
    name: docker.service
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
    scope: user
  ignore_errors: "{{ ansible_check_mode }}"

- name: Decouple rootless docker from user session
  command: "loginctl enable-linger {{ ansible_user_id }}"

- name: Retrieve XDG_RUNTIME_DIR environment
  become: false
  command: "echo $XDG_RUNTIME_DIR"
  register: xdg_runtime_dir_env

- name: Add DOCKER_HOST to local environment files
  become: false
  lineinfile:
    path: "{{ item }}"
    insertafter: EOF
    line: "export DOCKER_HOST=unix://{{ xdg_runtime_dir_env.stdout }}/docker.sock"
  with_items:
    - ".zshrc"
    - ".bashrc"
